version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mimastore-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MimaStore
      MYSQL_USER: mimastore_user
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - /home/ec2-user/app/db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - mima-network

networks:
  mima-network:
    external: true
