version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mimastore-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MimaStore
      MYSQL_USER: mimastore_user
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - /home/ec2-user/app/db_data:/var/lib/mysql
      - ./scriptpcro.sql:/docker-entrypoint-initdb.d/01-scriptpcro.sql:ro
    networks:
      - mima-network
#Rede para criação!
networks:
  mima-network:
    external: true
